### ISSUE TITLE
Wont accept the file

### ISSUE THREAD

**Issue by StabbyAlbert** [fahrennheit/zombsroyaleio-hack#8]
Using mac, on dev mode. I tried dragging the zombs-royale hacks master folder and it won't work. I also tried dragging the "Hack file" into the extension feed. But same message displayed. Is it just my computer or im doing somthing wrong?

**Comment by fahrennheit** [comment]
Hmm, try disabling your antivirus?

**Comment by StabbyAlbert** [comment]
@fahrennheit I am on mac sorry, can u talk to me on discord? stabbyalbert#5845

**Comment by fahrennheit** [comment]
I do not have discord, sorry :( but if disabling antivirus doesn't work, then I will have to find a solution since the hack is quite unstable right now, it works on some computers and not on others.
